# Generated by Django 6.0.4 on 2026-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_zip_code_quotation_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
